/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HashTable;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());


        HashTable<Object, Integer> salary = new HashTable<Object, Integer>();
        salary.add("John", 300);
        salary.add("Sally", 400);
        salary.add("Tom", 200);
        salary.add("Jade", 100);

        System.out.println("The size is => " + salary.getSize());
        System.out.println("The Sally allowance is => " + salary.get("Sally"));
        System.out.println("Delete Sally => " + salary.remove("Sally"));
        System.out.println("The size is => " + salary.getSize());

        String test ="Once upon a time, there was a brave princess who...";
        System.out.println("The Repeated Woed Is ---> "+salary.repeatedWord(test.toLowerCase()));

        System.out.println("The size is => " + salary.getSize());

    }
}
