/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HashTable;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    HashTable<Object, Integer> salary = new HashTable<Object, Integer>();

    @Test
    void testHashMap(){
        salary.add("John", 300);
        salary.add("Sally", 400);
        salary.add("Jade", 100);
        System.out.println("Delete Sally => " + salary.remove("Sally"));
        System.out.println("The size is => " + salary.getSize());
        assertTrue(salary.getSize()==2);
    }
    @Test
    public void testRepeatedWord(){

        String test ="Once upon a time, there was a brave princess who...";
        assertEquals(salary.repeatedWord(test.toLowerCase()),"a");
    }
    @Test
    public void testRepeatedWordRegardlessLowerOrUpperCase()
    {
        String test = "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way – in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only...";
        assertEquals(salary.repeatedWord(test.toLowerCase()),"it");
    }
    @Test
    public void testReapeatedWordWithSymbol(){
        String test = "It was a queer, sultry summer, the summer they electrocuted the Rosenbergs, and I didn't know what I was doing in New York...";
        assertEquals(salary.repeatedWord(test.toLowerCase()),"summer");
    }
}
