/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenges;

import Insertion.Sort;


import java.util.Arrays;

public class App  {

    public String getGreeting() {
        return "Hello World!";
    }



    public static void main(String[] args) {
        System.out.println(new App().getGreeting());


        Integer[] array = new Integer[]{8,4,23,42,16,15};
        Sort<Integer> insertionsort = new Sort<>();
        System.out.println(Arrays.toString(insertionsort.insertionSort(array)));
    }



}
