/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tree;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        BinaryTree tree = new BinaryTree();
        tree.setRoot(new Node(2));
        tree.getRoot().setLeft(new Node(7));
        tree.getRoot().setRight(new Node(5));
        tree.getRoot().getLeft().setRight(new Node(6));
        tree.getRoot().getLeft().getRight().setLeft(new Node(1));
        tree.getRoot().getLeft().getRight().setRight(new Node(11));
        tree.getRoot().getRight().setRight(new Node(9));
        tree.getRoot().getRight().getRight().setLeft(new Node(4));

        System.out.println(tree.maxValue());
    }
}
