/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenges;

import Insertion.MargeSort;
import Insertion.Sort;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    Integer[] integerArr= new Integer[]{5, 25, 30, 15, 10};

    @Test
    public void testInsertionSort() {
        Sort integerSort = new Sort<>();
        assertArrayEquals(new Integer[]{5, 10, 15, 25, 30}, integerSort.insertionSort(integerArr));
    }

    @Test
    public void testMergeSort() {
        MargeSort mergeSort= new MargeSort();
        assertArrayEquals(new Integer[]{5, 10, 15, 25, 30}, mergeSort.mergeSort(integerArr));
    }
}
